require 'rubygems'
require 'rake'

task :default => [:examples]
 
task :examples do
  sh 'jasnode spec'
end

namespace :test do
  task :units do
    sh 'jasnode spec'
  end
end

task :cruise do
  sh 'jasnode spec'
end
